-- ヤンクしたテキストをクリップボードにも残す
vim.api.nvim_set_option("clipboard", "unnamedplus")
-- 行番号を表示する
vim.api.nvim_set_option("number", true)
-- 行番号表示の左に1文字分の列を表示しておく(gitsigns用)
vim.api.nvim_set_option("signcolumn", "yes:1")
-- スクロール時に画面端に5行分の余裕をもたせる
vim.api.nvim_set_option("scrolloff", 5)
-- <C-a>や<C-x>で数を増減させる際、0埋め数字であっても10進数として扱う
vim.api.nvim_set_option("nrformats", "")
-- タブ文字を空白に展開する
vim.api.nvim_set_option("expandtab", true)
-- 画面上でタブ文字が占める幅を2文字分にする
vim.api.nvim_set_option("tabstop", 2)
-- 自動インデントでずれる幅を2文字分にする
vim.api.nvim_set_option("shiftwidth", 2)
-- 連続した空白に対してタブキーやバックスペースキーでカーソルが動く幅を2文字分にする
vim.api.nvim_set_option("softtabstop", 2)
-- 前回の検索パターンが存在するとき、それにマッチするテキストを全て強調表示する
vim.api.nvim_set_option("hlsearch", true)
-- 検索コマンドを打ち込んでいる間にも、打ち込んだところまでのパターンがマッチするテキストを、すぐに表示する
vim.api.nvim_set_option("incsearch", true)
